# Pulsar Starter 示例配置文件
# 复制此文件为 application.yml 并根据实际环境修改配置

spring:
  pulsar:
    # 是否启用 Pulsar（可以通过 @EnablePulsar 注解的 enabled 属性覆盖）
    enabled: true
    
    # Pulsar 服务地址
    service-url: pulsar://localhost:6650

    # 生产者配置
    producer:
      # 默认主题（可选）
      topic: example-default-topic
      # 发送超时时间
      send-timeout: 30s
      # 队列满时是否阻塞
      block-if-queue-full: false
      # 最大待发送消息数
      max-pending-messages: 1000
      # 是否启用批量发送
      batching-enabled: true
      # 批量发送最大消息数
      batching-max-messages: 1000
      # 批量发送最大延迟时间
      batching-max-publish-delay: 10ms
    
    # 消费者配置
    consumer:
      # 默认订阅名称
      subscription-name: example-subscription
      # 订阅类型：Exclusive, Shared, Failover, Key_Shared
      subscription-type: Exclusive
      # 消息确认超时时间
      ack-timeout: 30s
      # 接收队列大小
      receiver-queue-size: 1000
      # 队列满时是否自动确认最旧的分块消息
      auto-ack-oldest-chunked-message-on-queue-full: false
    
    # 客户端配置
    client:
      # 操作超时时间
      operation-timeout: 30s
      # 连接超时时间
      connection-timeout: 10s
      # IO 线程数
      num-io-threads: 1
      # 监听器线程数
      num-listener-threads: 1
    
    # 认证配置
    authentication:
      # 是否启用认证
      enabled: false
      # JWT Token（如果使用 Token 认证）
      # token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LXVzZXIifQ.9OHgpX0q7_7z1c5Q2X1Zn8X7c5Q2X1Zn8X7c5Q2X1Zn8
      # 认证插件类名
      # auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      # 认证参数
      # auth-params:
      #   token: your-token-here
    
    # 重试配置
    retry:
      # 是否启用重试
      enabled: true
      # 最大重试次数
      max-retries: 3
      # 初始延迟时间（毫秒）
      initial-delay: 1000
      # 延迟倍数
      multiplier: 2.0
      # 最大延迟时间（毫秒）
      max-delay: 30000
      # 是否使用随机延迟（避免雪崩效应）
      use-random-delay: true
    
    # 死信队列配置
    dead-letter:
      # 是否启用死信队列
      enabled: false
    
    # 健康检查配置
    health:
      # 是否启用健康检查
      enabled: true
    
    # 事务配置
    transaction:
      # 是否启用事务支持
      enabled: false

# 日志配置
logging:
  level:
    # Pulsar Starter 日志级别
    com.github.spring.mq.pulsar: INFO
    # Pulsar 客户端日志级别
    org.apache.pulsar: WARN
    # 示例服务日志级别
    com.github.spring.mq.pulsar.example: DEBUG

# 服务器配置（用于示例 REST API）
server:
  port: 8080

# 应用信息
info:
  app:
    name: Pulsar Starter Example
    description: Example application demonstrating Pulsar Starter features
    version: 1.0.0